package Entity;
// Generated 18-ago-2015 14:13:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Actividades generated by hbm2java
 */
public class Actividades  implements java.io.Serializable {


     private BigDecimal codigoActividad;
     private String descripcion;
     private String nombre;
     private Set rolActividads = new HashSet(0);

    public Actividades() {
    }

	
    public Actividades(BigDecimal codigoActividad, String descripcion, String nombre) {
        this.codigoActividad = codigoActividad;
        this.descripcion = descripcion;
        this.nombre = nombre;
    }
    public Actividades(BigDecimal codigoActividad, String descripcion, String nombre, Set rolActividads) {
       this.codigoActividad = codigoActividad;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.rolActividads = rolActividads;
    }
   
    public BigDecimal getCodigoActividad() {
        return this.codigoActividad;
    }
    
    public void setCodigoActividad(BigDecimal codigoActividad) {
        this.codigoActividad = codigoActividad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getRolActividads() {
        return this.rolActividads;
    }
    
    public void setRolActividads(Set rolActividads) {
        this.rolActividads = rolActividads;
    }




}


