package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actividades generated by hbm2java
 */
@Entity
@Table(name="actividades"
    ,schema="public"
)
public class Actividades  implements java.io.Serializable {


     private BigDecimal codigoActividad;
     private String descripcion;
     private String nombre;
     private Set rolActividads = new HashSet(0);

    public Actividades() {
    }

	
    public Actividades(BigDecimal codigoActividad, String descripcion, String nombre) {
        this.codigoActividad = codigoActividad;
        this.descripcion = descripcion;
        this.nombre = nombre;
    }
    public Actividades(BigDecimal codigoActividad, String descripcion, String nombre, Set rolActividads) {
       this.codigoActividad = codigoActividad;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.rolActividads = rolActividads;
    }
   
     @Id 

    
    @Column(name="codigo_actividad", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodigoActividad() {
        return this.codigoActividad;
    }
    
    public void setCodigoActividad(BigDecimal codigoActividad) {
        this.codigoActividad = codigoActividad;
    }

    
    @Column(name="descripcion", nullable=false, length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="actividades")
    public Set getRolActividads() {
        return this.rolActividads;
    }
    
    public void setRolActividads(Set rolActividads) {
        this.rolActividads = rolActividads;
    }




}


