package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ajuste generated by hbm2java
 */
@Entity
@Table(name="ajuste"
    ,schema="public"
)
public class Ajuste  implements java.io.Serializable {


     private BigDecimal codAjuste;
     private Usuario usuario;
     private AñoFestivo añoFestivo;
     private Date fechaInicial;
     private Date fechaFinal;
     private BigDecimal rango;
     private BigDecimal periodo;
     private BigDecimal numHoras;
     private String horaInicial;
     private String horaFinal;
     private String horaInicialFincho;
     private String horaFinalFincho;
     private Long horasProfesor;
     private Long horasasesoriaDia;
     private Set diases = new HashSet(0);
     private Set disponibilidads = new HashSet(0);

    public Ajuste() {
    }

	
    public Ajuste(BigDecimal codAjuste, Usuario usuario, Date fechaInicial, Date fechaFinal, BigDecimal rango, BigDecimal periodo, BigDecimal numHoras, String horaInicial, String horaFinal, String horaInicialFincho, String horaFinalFincho) {
        this.codAjuste = codAjuste;
        this.usuario = usuario;
        this.fechaInicial = fechaInicial;
        this.fechaFinal = fechaFinal;
        this.rango = rango;
        this.periodo = periodo;
        this.numHoras = numHoras;
        this.horaInicial = horaInicial;
        this.horaFinal = horaFinal;
        this.horaInicialFincho = horaInicialFincho;
        this.horaFinalFincho = horaFinalFincho;
    }
    public Ajuste(BigDecimal codAjuste, Usuario usuario, AñoFestivo añoFestivo, Date fechaInicial, Date fechaFinal, BigDecimal rango, BigDecimal periodo, BigDecimal numHoras, String horaInicial, String horaFinal, String horaInicialFincho, String horaFinalFincho, Long horasProfesor, Long horasasesoriaDia, Set diases, Set disponibilidads) {
       this.codAjuste = codAjuste;
       this.usuario = usuario;
       this.añoFestivo = añoFestivo;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.rango = rango;
       this.periodo = periodo;
       this.numHoras = numHoras;
       this.horaInicial = horaInicial;
       this.horaFinal = horaFinal;
       this.horaInicialFincho = horaInicialFincho;
       this.horaFinalFincho = horaFinalFincho;
       this.horasProfesor = horasProfesor;
       this.horasasesoriaDia = horasasesoriaDia;
       this.diases = diases;
       this.disponibilidads = disponibilidads;
    }
   
     @Id 

    
    @Column(name="cod_ajuste", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodAjuste() {
        return this.codAjuste;
    }
    
    public void setCodAjuste(BigDecimal codAjuste) {
        this.codAjuste = codAjuste;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pege_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="festivo")
    public AñoFestivo getAñoFestivo() {
        return this.añoFestivo;
    }
    
    public void setAñoFestivo(AñoFestivo añoFestivo) {
        this.añoFestivo = añoFestivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicial", nullable=false, length=13)
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_final", nullable=false, length=13)
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    
    @Column(name="rango", nullable=false, precision=131089, scale=0)
    public BigDecimal getRango() {
        return this.rango;
    }
    
    public void setRango(BigDecimal rango) {
        this.rango = rango;
    }

    
    @Column(name="periodo", nullable=false, precision=131089, scale=0)
    public BigDecimal getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(BigDecimal periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="num_horas", nullable=false, precision=131089, scale=0)
    public BigDecimal getNumHoras() {
        return this.numHoras;
    }
    
    public void setNumHoras(BigDecimal numHoras) {
        this.numHoras = numHoras;
    }

    
    @Column(name="hora_inicial", nullable=false)
    public String getHoraInicial() {
        return this.horaInicial;
    }
    
    public void setHoraInicial(String horaInicial) {
        this.horaInicial = horaInicial;
    }

    
    @Column(name="hora_final", nullable=false)
    public String getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(String horaFinal) {
        this.horaFinal = horaFinal;
    }

    
    @Column(name="hora_inicial_fincho", nullable=false)
    public String getHoraInicialFincho() {
        return this.horaInicialFincho;
    }
    
    public void setHoraInicialFincho(String horaInicialFincho) {
        this.horaInicialFincho = horaInicialFincho;
    }

    
    @Column(name="hora_final_fincho", nullable=false)
    public String getHoraFinalFincho() {
        return this.horaFinalFincho;
    }
    
    public void setHoraFinalFincho(String horaFinalFincho) {
        this.horaFinalFincho = horaFinalFincho;
    }

    
    @Column(name="horas_profesor", precision=10, scale=0)
    public Long getHorasProfesor() {
        return this.horasProfesor;
    }
    
    public void setHorasProfesor(Long horasProfesor) {
        this.horasProfesor = horasProfesor;
    }

    
    @Column(name="horasasesoria_dia", precision=10, scale=0)
    public Long getHorasasesoriaDia() {
        return this.horasasesoriaDia;
    }
    
    public void setHorasasesoriaDia(Long horasasesoriaDia) {
        this.horasasesoriaDia = horasasesoriaDia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ajuste")
    public Set getDiases() {
        return this.diases;
    }
    
    public void setDiases(Set diases) {
        this.diases = diases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ajuste")
    public Set getDisponibilidads() {
        return this.disponibilidads;
    }
    
    public void setDisponibilidads(Set disponibilidads) {
        this.disponibilidads = disponibilidads;
    }




}


