package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Aofestivo generated by hbm2java
 */
@Entity
@Table(name="aofestivo"
    ,schema="public"
)
public class Aofestivo  implements java.io.Serializable {


     private BigDecimal codAo;
     private String ao;
     private Set festivoses = new HashSet(0);

    public Aofestivo() {
    }

	
    public Aofestivo(BigDecimal codAo, String ao) {
        this.codAo = codAo;
        this.ao = ao;
    }
    public Aofestivo(BigDecimal codAo, String ao, Set festivoses) {
       this.codAo = codAo;
       this.ao = ao;
       this.festivoses = festivoses;
    }
   
     @Id 

    
    @Column(name="cod_ao", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodAo() {
        return this.codAo;
    }
    
    public void setCodAo(BigDecimal codAo) {
        this.codAo = codAo;
    }

    
    @Column(name="ao", nullable=false)
    public String getAo() {
        return this.ao;
    }
    
    public void setAo(String ao) {
        this.ao = ao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aofestivo")
    public Set getFestivoses() {
        return this.festivoses;
    }
    
    public void setFestivoses(Set festivoses) {
        this.festivoses = festivoses;
    }




}


