package Entity;
// Generated 18-ago-2015 14:13:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Asesoria generated by hbm2java
 */
public class Asesoria  implements java.io.Serializable {


     private BigDecimal codAsesoria;
     private Disponibilidad disponibilidad;
     private Ubicacion ubicacion;
     private Date fechaAsesoria;
     private BigDecimal codigoProyecto;
     private String description;
     private String tipoAsesoria;
     private Date horaIni;
     private Date horaFin;
     private Set estadosAsesorias = new HashSet(0);
     private Set detalleAsesorias = new HashSet(0);
     private Set asistentes = new HashSet(0);
     private Set tareases = new HashSet(0);

    public Asesoria() {
    }

	
    public Asesoria(BigDecimal codAsesoria, Disponibilidad disponibilidad, Ubicacion ubicacion, Date fechaAsesoria, BigDecimal codigoProyecto, String description, String tipoAsesoria) {
        this.codAsesoria = codAsesoria;
        this.disponibilidad = disponibilidad;
        this.ubicacion = ubicacion;
        this.fechaAsesoria = fechaAsesoria;
        this.codigoProyecto = codigoProyecto;
        this.description = description;
        this.tipoAsesoria = tipoAsesoria;
    }
    public Asesoria(BigDecimal codAsesoria, Disponibilidad disponibilidad, Ubicacion ubicacion, Date fechaAsesoria, BigDecimal codigoProyecto, String description, String tipoAsesoria, Date horaIni, Date horaFin, Set estadosAsesorias, Set detalleAsesorias, Set asistentes, Set tareases) {
       this.codAsesoria = codAsesoria;
       this.disponibilidad = disponibilidad;
       this.ubicacion = ubicacion;
       this.fechaAsesoria = fechaAsesoria;
       this.codigoProyecto = codigoProyecto;
       this.description = description;
       this.tipoAsesoria = tipoAsesoria;
       this.horaIni = horaIni;
       this.horaFin = horaFin;
       this.estadosAsesorias = estadosAsesorias;
       this.detalleAsesorias = detalleAsesorias;
       this.asistentes = asistentes;
       this.tareases = tareases;
    }
   
    public BigDecimal getCodAsesoria() {
        return this.codAsesoria;
    }
    
    public void setCodAsesoria(BigDecimal codAsesoria) {
        this.codAsesoria = codAsesoria;
    }
    public Disponibilidad getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Disponibilidad disponibilidad) {
        this.disponibilidad = disponibilidad;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Date getFechaAsesoria() {
        return this.fechaAsesoria;
    }
    
    public void setFechaAsesoria(Date fechaAsesoria) {
        this.fechaAsesoria = fechaAsesoria;
    }
    public BigDecimal getCodigoProyecto() {
        return this.codigoProyecto;
    }
    
    public void setCodigoProyecto(BigDecimal codigoProyecto) {
        this.codigoProyecto = codigoProyecto;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getTipoAsesoria() {
        return this.tipoAsesoria;
    }
    
    public void setTipoAsesoria(String tipoAsesoria) {
        this.tipoAsesoria = tipoAsesoria;
    }
    public Date getHoraIni() {
        return this.horaIni;
    }
    
    public void setHoraIni(Date horaIni) {
        this.horaIni = horaIni;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public Set getEstadosAsesorias() {
        return this.estadosAsesorias;
    }
    
    public void setEstadosAsesorias(Set estadosAsesorias) {
        this.estadosAsesorias = estadosAsesorias;
    }
    public Set getDetalleAsesorias() {
        return this.detalleAsesorias;
    }
    
    public void setDetalleAsesorias(Set detalleAsesorias) {
        this.detalleAsesorias = detalleAsesorias;
    }
    public Set getAsistentes() {
        return this.asistentes;
    }
    
    public void setAsistentes(Set asistentes) {
        this.asistentes = asistentes;
    }
    public Set getTareases() {
        return this.tareases;
    }
    
    public void setTareases(Set tareases) {
        this.tareases = tareases;
    }




}


