package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asesoria generated by hbm2java
 */
@Entity
@Table(name="asesoria"
    ,schema="public"
)
public class Asesoria  implements java.io.Serializable {


     private BigDecimal codAsesoria;
     private Disponibilidad disponibilidad;
     private Ubicacion ubicacion;
     private Date fechaAsesoria;
     private BigDecimal codigoProyecto;
     private String horaAsesoria;
     private String horaFinal;
     private String description;
     private String tipoAsesoria;
     private Set estadosAsesorias = new HashSet(0);
     private Set detalleAsesorias = new HashSet(0);
     private Set asistentes = new HashSet(0);
     private Set tareases = new HashSet(0);

    public Asesoria() {
    }

	
    public Asesoria(BigDecimal codAsesoria, Disponibilidad disponibilidad, Ubicacion ubicacion, Date fechaAsesoria, BigDecimal codigoProyecto, String horaAsesoria, String horaFinal, String description, String tipoAsesoria) {
        this.codAsesoria = codAsesoria;
        this.disponibilidad = disponibilidad;
        this.ubicacion = ubicacion;
        this.fechaAsesoria = fechaAsesoria;
        this.codigoProyecto = codigoProyecto;
        this.horaAsesoria = horaAsesoria;
        this.horaFinal = horaFinal;
        this.description = description;
        this.tipoAsesoria = tipoAsesoria;
    }
    public Asesoria(BigDecimal codAsesoria, Disponibilidad disponibilidad, Ubicacion ubicacion, Date fechaAsesoria, BigDecimal codigoProyecto, String horaAsesoria, String horaFinal, String description, String tipoAsesoria, Set estadosAsesorias, Set detalleAsesorias, Set asistentes, Set tareases) {
       this.codAsesoria = codAsesoria;
       this.disponibilidad = disponibilidad;
       this.ubicacion = ubicacion;
       this.fechaAsesoria = fechaAsesoria;
       this.codigoProyecto = codigoProyecto;
       this.horaAsesoria = horaAsesoria;
       this.horaFinal = horaFinal;
       this.description = description;
       this.tipoAsesoria = tipoAsesoria;
       this.estadosAsesorias = estadosAsesorias;
       this.detalleAsesorias = detalleAsesorias;
       this.asistentes = asistentes;
       this.tareases = tareases;
    }
   
     @Id 

    
    @Column(name="cod_asesoria", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodAsesoria() {
        return this.codAsesoria;
    }
    
    public void setCodAsesoria(BigDecimal codAsesoria) {
        this.codAsesoria = codAsesoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_dis", nullable=false)
    public Disponibilidad getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Disponibilidad disponibilidad) {
        this.disponibilidad = disponibilidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ubicacion", nullable=false)
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_asesoria", nullable=false, length=13)
    public Date getFechaAsesoria() {
        return this.fechaAsesoria;
    }
    
    public void setFechaAsesoria(Date fechaAsesoria) {
        this.fechaAsesoria = fechaAsesoria;
    }

    
    @Column(name="codigo_proyecto", nullable=false, precision=131089, scale=0)
    public BigDecimal getCodigoProyecto() {
        return this.codigoProyecto;
    }
    
    public void setCodigoProyecto(BigDecimal codigoProyecto) {
        this.codigoProyecto = codigoProyecto;
    }

    
    @Column(name="hora_asesoria", nullable=false)
    public String getHoraAsesoria() {
        return this.horaAsesoria;
    }
    
    public void setHoraAsesoria(String horaAsesoria) {
        this.horaAsesoria = horaAsesoria;
    }

    
    @Column(name="hora_final", nullable=false)
    public String getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(String horaFinal) {
        this.horaFinal = horaFinal;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="tipo_asesoria", nullable=false)
    public String getTipoAsesoria() {
        return this.tipoAsesoria;
    }
    
    public void setTipoAsesoria(String tipoAsesoria) {
        this.tipoAsesoria = tipoAsesoria;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asesoria")
    public Set getEstadosAsesorias() {
        return this.estadosAsesorias;
    }
    
    public void setEstadosAsesorias(Set estadosAsesorias) {
        this.estadosAsesorias = estadosAsesorias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asesoria")
    public Set getDetalleAsesorias() {
        return this.detalleAsesorias;
    }
    
    public void setDetalleAsesorias(Set detalleAsesorias) {
        this.detalleAsesorias = detalleAsesorias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asesoria")
    public Set getAsistentes() {
        return this.asistentes;
    }
    
    public void setAsistentes(Set asistentes) {
        this.asistentes = asistentes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asesoria")
    public Set getTareases() {
        return this.tareases;
    }
    
    public void setTareases(Set tareases) {
        this.tareases = tareases;
    }




}


