package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Asistente generated by hbm2java
 */
@Entity
@Table(name="asistente"
    ,schema="public"
)
public class Asistente  implements java.io.Serializable {


     private BigDecimal codAsis;
     private Asesoria asesoria;
     private Usuario usuario;
     private String asistencia;

    public Asistente() {
    }

    public Asistente(BigDecimal codAsis, Asesoria asesoria, Usuario usuario, String asistencia) {
       this.codAsis = codAsis;
       this.asesoria = asesoria;
       this.usuario = usuario;
       this.asistencia = asistencia;
    }
   
     @Id 

    
    @Column(name="cod_asis", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodAsis() {
        return this.codAsis;
    }
    
    public void setCodAsis(BigDecimal codAsis) {
        this.codAsis = codAsis;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_asesoria", nullable=false)
    public Asesoria getAsesoria() {
        return this.asesoria;
    }
    
    public void setAsesoria(Asesoria asesoria) {
        this.asesoria = asesoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estudiante", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="asistencia", nullable=false)
    public String getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(String asistencia) {
        this.asistencia = asistencia;
    }




}


