package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * A�oFestivo generated by hbm2java
 */
@Entity
@Table(name="año_festivo"
    ,schema="public"
)
public class AñoFestivo  implements java.io.Serializable {


     private long codAño;
     private String año;
     private Set ajustes = new HashSet(0);
     private Set festivoses = new HashSet(0);

    public AñoFestivo() {
    }

	
    public AñoFestivo(long codAño, String año) {
        this.codAño = codAño;
        this.año = año;
    }
    public AñoFestivo(long codAño, String año, Set ajustes, Set festivoses) {
       this.codAño = codAño;
       this.año = año;
       this.ajustes = ajustes;
       this.festivoses = festivoses;
    }
   
     @Id 

    
    @Column(name="cod_año", unique=true, nullable=false, precision=10, scale=0)
    public long getCodAño() {
        return this.codAño;
    }
    
    public void setCodAño(long codAño) {
        this.codAño = codAño;
    
    }
    
    @Column(name="año", nullable=false, length=10)
    public String getAño() {
        return this.año;
    }
    
    public void setAño(String año) {
        this.año = año;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="a�oFestivo")
    public Set getAjustes() {
        return this.ajustes;
    }
    
    public void setAjustes(Set ajustes) {
        this.ajustes = ajustes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="a�oFestivo")
    public Set getFestivoses() {
        return this.festivoses;
    }
    
    public void setFestivoses(Set festivoses) {
        this.festivoses = festivoses;
    }




}


