package Entity;
// Generated 22-jul-2015 14:32:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Calendario generated by hbm2java
 */
public class Calendario  implements java.io.Serializable {


     private long codCalendario;
     private Usuario usuario;
     private String descripcion;
     private Date fechaInicial;
     private Date fechaFinal;
     private String horaInicial;
     private String horaFinal;

    public Calendario() {
    }

	
    public Calendario(long codCalendario, String descripcion, Date fechaInicial, Date fechaFinal) {
        this.codCalendario = codCalendario;
        this.descripcion = descripcion;
        this.fechaInicial = fechaInicial;
        this.fechaFinal = fechaFinal;
    }
    public Calendario(long codCalendario, Usuario usuario, String descripcion, Date fechaInicial, Date fechaFinal, String horaInicial, String horaFinal) {
       this.codCalendario = codCalendario;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.horaInicial = horaInicial;
       this.horaFinal = horaFinal;
    }
   
    public long getCodCalendario() {
        return this.codCalendario;
    }
    
    public void setCodCalendario(long codCalendario) {
        this.codCalendario = codCalendario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public String getHoraInicial() {
        return this.horaInicial;
    }
    
    public void setHoraInicial(String horaInicial) {
        this.horaInicial = horaInicial;
    }
    public String getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(String horaFinal) {
        this.horaFinal = horaFinal;
    }




}


