package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendario generated by hbm2java
 */
@Entity
@Table(name="calendario"
    ,schema="public"
)
public class Calendario  implements java.io.Serializable {


     private long codCalendario;
     private Usuario usuario;
     private String descripcion;
     private Date fechaInicial;
     private Date fechaFinal;
     private String horaInicial;
     private String horaFinal;

    public Calendario() {
    }

	
    public Calendario(long codCalendario, String descripcion, Date fechaInicial, Date fechaFinal) {
        this.codCalendario = codCalendario;
        this.descripcion = descripcion;
        this.fechaInicial = fechaInicial;
        this.fechaFinal = fechaFinal;
    }
    public Calendario(long codCalendario, Usuario usuario, String descripcion, Date fechaInicial, Date fechaFinal, String horaInicial, String horaFinal) {
       this.codCalendario = codCalendario;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.horaInicial = horaInicial;
       this.horaFinal = horaFinal;
    }
   
     @Id 

    
    @Column(name="cod_calendario", unique=true, nullable=false, precision=10, scale=0)
    public long getCodCalendario() {
        return this.codCalendario;
    }
    
    public void setCodCalendario(long codCalendario) {
        this.codCalendario = codCalendario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pege_id")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="descripcion", nullable=false, length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicial", nullable=false, length=13)
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_final", nullable=false, length=13)
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    
    @Column(name="hora_inicial", length=6)
    public String getHoraInicial() {
        return this.horaInicial;
    }
    
    public void setHoraInicial(String horaInicial) {
        this.horaInicial = horaInicial;
    }

    
    @Column(name="hora_final", length=6)
    public String getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(String horaFinal) {
        this.horaFinal = horaFinal;
    }




}


