package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendario generated by hbm2java
 */
@Entity
@Table(name="calendario"
    ,schema="public"
)
public class Calendario  implements java.io.Serializable {


     private long codCalemndario;
     private Usuario usuario;
     private Date fechaInicial;
     private Date fechaFinal;
     private String horaInicial;
     private String horaFinal;
     private String actividad;

    public Calendario() {
    }

	
    public Calendario(long codCalemndario, Date fechaInicial, Date fechaFinal) {
        this.codCalemndario = codCalemndario;
        this.fechaInicial = fechaInicial;
        this.fechaFinal = fechaFinal;
    }
    public Calendario(long codCalemndario, Usuario usuario, Date fechaInicial, Date fechaFinal, String horaInicial, String horaFinal, String actividad) {
       this.codCalemndario = codCalemndario;
       this.usuario = usuario;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.horaInicial = horaInicial;
       this.horaFinal = horaFinal;
       this.actividad = actividad;
    }
   
     @Id 

    
    @Column(name="cod_calemndario", unique=true, nullable=false, precision=10, scale=0)
    public long getCodCalemndario() {
        return this.codCalemndario;
    }
    
    public void setCodCalemndario(long codCalemndario) {
        this.codCalemndario = codCalemndario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pege_id")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicial", nullable=false, length=13)
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_final", nullable=false, length=13)
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    
    @Column(name="hora_inicial", length=10)
    public String getHoraInicial() {
        return this.horaInicial;
    }
    
    public void setHoraInicial(String horaInicial) {
        this.horaInicial = horaInicial;
    }

    
    @Column(name="hora_final", length=10)
    public String getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(String horaFinal) {
        this.horaFinal = horaFinal;
    }

    
    @Column(name="actividad", length=200)
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }

    @Override
    public String toString() {
        return ""+codCalemndario;
    }




}


