package Entity;
// Generated 22-jul-2015 14:32:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private BigDecimal codCalificacion;
     private Proyectos proyectos;
     private String nota;

    public Calificacion() {
    }

    public Calificacion(BigDecimal codCalificacion, Proyectos proyectos, String nota) {
       this.codCalificacion = codCalificacion;
       this.proyectos = proyectos;
       this.nota = nota;
    }
   
    public BigDecimal getCodCalificacion() {
        return this.codCalificacion;
    }
    
    public void setCodCalificacion(BigDecimal codCalificacion) {
        this.codCalificacion = codCalificacion;
    }
    public Proyectos getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Proyectos proyectos) {
        this.proyectos = proyectos;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }




}


