package Entity;
// Generated 02-jun-2015 13:38:41 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Calificacion generated by hbm2java
 */
@Entity
@Table(name="calificacion"
    ,schema="public"
)
public class Calificacion  implements java.io.Serializable {


     private BigDecimal codCalificacion;
     private Proyectos proyectos;
     private String nota;

    public Calificacion() {
    }

    public Calificacion(BigDecimal codCalificacion, Proyectos proyectos, String nota) {
       this.codCalificacion = codCalificacion;
       this.proyectos = proyectos;
       this.nota = nota;
    }
   
     @Id 

    
    @Column(name="cod_calificacion", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodCalificacion() {
        return this.codCalificacion;
    }
    
    public void setCodCalificacion(BigDecimal codCalificacion) {
        this.codCalificacion = codCalificacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_proyecto", nullable=false)
    public Proyectos getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Proyectos proyectos) {
        this.proyectos = proyectos;
    }

    
    @Column(name="nota", nullable=false)
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }




}


