package Entity;
// Generated 02-jun-2015 13:38:41 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Correospersona generated by hbm2java
 */
@Entity
@Table(name="correospersona"
    ,schema="public"
)
public class Correospersona  implements java.io.Serializable {


     private BigDecimal codCorreo;
     private Persona persona;
     private String correo;

    public Correospersona() {
    }

    public Correospersona(BigDecimal codCorreo, Persona persona, String correo) {
       this.codCorreo = codCorreo;
       this.persona = persona;
       this.correo = correo;
    }
   
     @Id 

    
    @Column(name="cod_correo", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodCorreo() {
        return this.codCorreo;
    }
    
    public void setCodCorreo(BigDecimal codCorreo) {
        this.codCorreo = codCorreo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpersona", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="correo", nullable=false)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


