package Entity;
// Generated 22-jul-2015 14:32:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Correospersona generated by hbm2java
 */
public class Correospersona  implements java.io.Serializable {


     private BigDecimal codCorreo;
     private Persona persona;
     private String correo;

    public Correospersona() {
    }

    public Correospersona(BigDecimal codCorreo, Persona persona, String correo) {
       this.codCorreo = codCorreo;
       this.persona = persona;
       this.correo = correo;
    }
   
    public BigDecimal getCodCorreo() {
        return this.codCorreo;
    }
    
    public void setCodCorreo(BigDecimal codCorreo) {
        this.codCorreo = codCorreo;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


