package Entity;
// Generated 13-ago-2015 17:28:37 by Hibernate Tools 4.3.1



/**
 * DetalleAsesoria generated by hbm2java
 */
public class DetalleAsesoria  implements java.io.Serializable {


     private long codDetalle;
     private Asesoria asesoria;
     private String descripcion;

    public DetalleAsesoria() {
    }

	
    public DetalleAsesoria(long codDetalle, String descripcion) {
        this.codDetalle = codDetalle;
        this.descripcion = descripcion;
    }
    public DetalleAsesoria(long codDetalle, Asesoria asesoria, String descripcion) {
       this.codDetalle = codDetalle;
       this.asesoria = asesoria;
       this.descripcion = descripcion;
    }
   
    public long getCodDetalle() {
        return this.codDetalle;
    }
    
    public void setCodDetalle(long codDetalle) {
        this.codDetalle = codDetalle;
    }
    public Asesoria getAsesoria() {
        return this.asesoria;
    }
    
    public void setAsesoria(Asesoria asesoria) {
        this.asesoria = asesoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


