package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleAsesoria generated by hbm2java
 */
@Entity
@Table(name="detalle_asesoria"
    ,schema="public"
)
public class DetalleAsesoria  implements java.io.Serializable {


     private long codDetalle;
     private Asesoria asesoria;
     private String descripcion;

    public DetalleAsesoria() {
    }

	
    public DetalleAsesoria(long codDetalle, String descripcion) {
        this.codDetalle = codDetalle;
        this.descripcion = descripcion;
    }
    public DetalleAsesoria(long codDetalle, Asesoria asesoria, String descripcion) {
       this.codDetalle = codDetalle;
       this.asesoria = asesoria;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="cod_detalle", unique=true, nullable=false, precision=10, scale=0)
    public long getCodDetalle() {
        return this.codDetalle;
    }
    
    public void setCodDetalle(long codDetalle) {
        this.codDetalle = codDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_asesoria")
    public Asesoria getAsesoria() {
        return this.asesoria;
    }
    
    public void setAsesoria(Asesoria asesoria) {
        this.asesoria = asesoria;
    }

    
    @Column(name="descripcion", nullable=false, length=2000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


