package Entity;
// Generated 18-ago-2015 14:13:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Dia generated by hbm2java
 */
public class Dia  implements java.io.Serializable {


     private BigDecimal codigoDia;
     private Disponibilidad disponibilidad;
     private String dia;
     private String horaFinal;
     private String horaInicial;

    public Dia() {
    }

	
    public Dia(BigDecimal codigoDia, Disponibilidad disponibilidad, String dia) {
        this.codigoDia = codigoDia;
        this.disponibilidad = disponibilidad;
        this.dia = dia;
    }
    public Dia(BigDecimal codigoDia, Disponibilidad disponibilidad, String dia, String horaFinal, String horaInicial) {
       this.codigoDia = codigoDia;
       this.disponibilidad = disponibilidad;
       this.dia = dia;
       this.horaFinal = horaFinal;
       this.horaInicial = horaInicial;
    }
   
    public BigDecimal getCodigoDia() {
        return this.codigoDia;
    }
    
    public void setCodigoDia(BigDecimal codigoDia) {
        this.codigoDia = codigoDia;
    }
    public Disponibilidad getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Disponibilidad disponibilidad) {
        this.disponibilidad = disponibilidad;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(String horaFinal) {
        this.horaFinal = horaFinal;
    }
    public String getHoraInicial() {
        return this.horaInicial;
    }
    
    public void setHoraInicial(String horaInicial) {
        this.horaInicial = horaInicial;
    }




}


