package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0



import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dias generated by hbm2java
 */
@Entity
@Table(name="dias"
    ,schema="public"
)
public class Dias  implements java.io.Serializable {


     private BigDecimal codDias;
     private Ajuste ajuste;
     private String dia;

    public Dias() {
    }

    public Dias(BigDecimal codDias, Ajuste ajuste, String dia) {
       this.codDias = codDias;
       this.ajuste = ajuste;
       this.dia = dia;
    }
   
     @Id 

    
    @Column(name="cod_dias", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodDias() {
        return this.codDias;
    }
    
    public void setCodDias(BigDecimal codDias) {
        this.codDias = codDias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_ajuste", nullable=false)
    public Ajuste getAjuste() {
        return this.ajuste;
    }
    
    public void setAjuste(Ajuste ajuste) {
        this.ajuste = ajuste;
    }

    
    @Column(name="dia", nullable=false)
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }

    @Override
    public String toString() {
        return  ""+codDias;
    }


  




}


