package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DispoUsuario generated by hbm2java
 */
@Entity
@Table(name="dispo_usuario"
    ,schema="public"
)
public class DispoUsuario  implements java.io.Serializable {


     private BigDecimal dispoUsu;
     private Usuario usuario;
     private Disponibilidad disponibilidad;

    public DispoUsuario() {
    }

    public DispoUsuario(BigDecimal dispoUsu, Usuario usuario, Disponibilidad disponibilidad) {
       this.dispoUsu = dispoUsu;
       this.usuario = usuario;
       this.disponibilidad = disponibilidad;
    }
   
     @Id 

    
    @Column(name="dispo_usu", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getDispoUsu() {
        return this.dispoUsu;
    }
    
    public void setDispoUsu(BigDecimal dispoUsu) {
        this.dispoUsu = dispoUsu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pege_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_dis", nullable=false)
    public Disponibilidad getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Disponibilidad disponibilidad) {
        this.disponibilidad = disponibilidad;
    }




}


