package Entity;
// Generated 02-jun-2015 13:38:41 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DispoUsuario generated by hbm2java
 */
@Entity
@Table(name="dispo_usuario"
    ,schema="public"
)
public class DispoUsuario  implements java.io.Serializable {


     private BigDecimal codDispousu;
     private Usuario usuarioByProfesor;
     private Usuario usuarioByAdmon;
     private Disponibilidad disponibilidad;

    public DispoUsuario() {
    }

    public DispoUsuario(BigDecimal codDispousu, Usuario usuarioByProfesor, Usuario usuarioByAdmon, Disponibilidad disponibilidad) {
       this.codDispousu = codDispousu;
       this.usuarioByProfesor = usuarioByProfesor;
       this.usuarioByAdmon = usuarioByAdmon;
       this.disponibilidad = disponibilidad;
    }
   
     @Id 

    
    @Column(name="cod_dispousu", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodDispousu() {
        return this.codDispousu;
    }
    
    public void setCodDispousu(BigDecimal codDispousu) {
        this.codDispousu = codDispousu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profesor", nullable=false)
    public Usuario getUsuarioByProfesor() {
        return this.usuarioByProfesor;
    }
    
    public void setUsuarioByProfesor(Usuario usuarioByProfesor) {
        this.usuarioByProfesor = usuarioByProfesor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admon", nullable=false)
    public Usuario getUsuarioByAdmon() {
        return this.usuarioByAdmon;
    }
    
    public void setUsuarioByAdmon(Usuario usuarioByAdmon) {
        this.usuarioByAdmon = usuarioByAdmon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_dis", nullable=false)
    public Disponibilidad getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Disponibilidad disponibilidad) {
        this.disponibilidad = disponibilidad;
    }




}


