package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Disponibilidad generated by hbm2java
 */
@Entity
@Table(name="disponibilidad"
    ,schema="public"
)
public class Disponibilidad  implements java.io.Serializable {


     private BigDecimal codDis;
     private Ajuste ajuste;
     private Date fechaInicial;
     private Date fechaFinal;
     private Set asesorias = new HashSet(0);
     private Set dispoUsuarios = new HashSet(0);
     private Set nivelDisponibles = new HashSet(0);
     private Set dias = new HashSet(0);

    public Disponibilidad() {
    }

	
    public Disponibilidad(BigDecimal codDis, Ajuste ajuste, Date fechaInicial, Date fechaFinal) {
        this.codDis = codDis;
        this.ajuste = ajuste;
        this.fechaInicial = fechaInicial;
        this.fechaFinal = fechaFinal;
    }
    public Disponibilidad(BigDecimal codDis, Ajuste ajuste, Date fechaInicial, Date fechaFinal, Set asesorias, Set dispoUsuarios, Set nivelDisponibles, Set dias) {
       this.codDis = codDis;
       this.ajuste = ajuste;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.asesorias = asesorias;
       this.dispoUsuarios = dispoUsuarios;
       this.nivelDisponibles = nivelDisponibles;
       this.dias = dias;
    }
   
     @Id 

    
    @Column(name="cod_dis", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodDis() {
        return this.codDis;
    }
    
    public void setCodDis(BigDecimal codDis) {
        this.codDis = codDis;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_ajuste", nullable=false)
    public Ajuste getAjuste() {
        return this.ajuste;
    }
    
    public void setAjuste(Ajuste ajuste) {
        this.ajuste = ajuste;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicial", nullable=false, length=13)
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_final", nullable=false, length=13)
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="disponibilidad")
    public Set getAsesorias() {
        return this.asesorias;
    }
    
    public void setAsesorias(Set asesorias) {
        this.asesorias = asesorias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="disponibilidad")
    public Set getDispoUsuarios() {
        return this.dispoUsuarios;
    }
    
    public void setDispoUsuarios(Set dispoUsuarios) {
        this.dispoUsuarios = dispoUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="disponibilidad")
    public Set getNivelDisponibles() {
        return this.nivelDisponibles;
    }
    
    public void setNivelDisponibles(Set nivelDisponibles) {
        this.nivelDisponibles = nivelDisponibles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="disponibilidad")
    public Set getDias() {
        return this.dias;
    }
    
    public void setDias(Set dias) {
        this.dias = dias;
    }




}


