package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name="estados"
    ,schema="public"
)
public class Estados  implements java.io.Serializable {


     private BigDecimal codigoEstados;
     private String descripcion;
     private Set estadoProyectos = new HashSet(0);
     private Set estadosAsesorias = new HashSet(0);

    public Estados() {
    }

	
    public Estados(BigDecimal codigoEstados, String descripcion) {
        this.codigoEstados = codigoEstados;
        this.descripcion = descripcion;
    }
    public Estados(BigDecimal codigoEstados, String descripcion, Set estadoProyectos, Set estadosAsesorias) {
       this.codigoEstados = codigoEstados;
       this.descripcion = descripcion;
       this.estadoProyectos = estadoProyectos;
       this.estadosAsesorias = estadosAsesorias;
    }
   
     @Id 

    
    @Column(name="codigo_estados", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodigoEstados() {
        return this.codigoEstados;
    }
    
    public void setCodigoEstados(BigDecimal codigoEstados) {
        this.codigoEstados = codigoEstados;
    }

    
    @Column(name="descripcion", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estados")
    public Set getEstadoProyectos() {
        return this.estadoProyectos;
    }
    
    public void setEstadoProyectos(Set estadoProyectos) {
        this.estadoProyectos = estadoProyectos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estados")
    public Set getEstadosAsesorias() {
        return this.estadosAsesorias;
    }
    
    public void setEstadosAsesorias(Set estadosAsesorias) {
        this.estadosAsesorias = estadosAsesorias;
    }




}


