package Entity;
// Generated 18-ago-2015 14:13:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EstadosAsesoria generated by hbm2java
 */
public class EstadosAsesoria  implements java.io.Serializable {


     private BigDecimal codEstadoasee;
     private Asesoria asesoria;
     private Estados estados;

    public EstadosAsesoria() {
    }

    public EstadosAsesoria(BigDecimal codEstadoasee, Asesoria asesoria, Estados estados) {
       this.codEstadoasee = codEstadoasee;
       this.asesoria = asesoria;
       this.estados = estados;
    }
   
    public BigDecimal getCodEstadoasee() {
        return this.codEstadoasee;
    }
    
    public void setCodEstadoasee(BigDecimal codEstadoasee) {
        this.codEstadoasee = codEstadoasee;
    }
    public Asesoria getAsesoria() {
        return this.asesoria;
    }
    
    public void setAsesoria(Asesoria asesoria) {
        this.asesoria = asesoria;
    }
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }




}


