package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EstadosAsesoria generated by hbm2java
 */
@Entity
@Table(name="estados_asesoria"
    ,schema="public"
)
public class EstadosAsesoria  implements java.io.Serializable {


     private BigDecimal codEstadoasee;
     private Asesoria asesoria;
     private Estados estados;

    public EstadosAsesoria() {
    }

    public EstadosAsesoria(BigDecimal codEstadoasee, Asesoria asesoria, Estados estados) {
       this.codEstadoasee = codEstadoasee;
       this.asesoria = asesoria;
       this.estados = estados;
    }
   
     @Id 

    
    @Column(name="cod_estadoasee", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodEstadoasee() {
        return this.codEstadoasee;
    }
    
    public void setCodEstadoasee(BigDecimal codEstadoasee) {
        this.codEstadoasee = codEstadoasee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_asesoria", nullable=false)
    public Asesoria getAsesoria() {
        return this.asesoria;
    }
    
    public void setAsesoria(Asesoria asesoria) {
        this.asesoria = asesoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_estados", nullable=false)
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }




}


