package Entity;
// Generated 18-ago-2015 14:13:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EstadoProyecto generated by hbm2java
 */
public class EstadoProyecto  implements java.io.Serializable {


     private BigDecimal codEstadoproyec;
     private Estados estados;
     private Proyectos proyectos;

    public EstadoProyecto() {
    }

    public EstadoProyecto(BigDecimal codEstadoproyec, Estados estados, Proyectos proyectos) {
       this.codEstadoproyec = codEstadoproyec;
       this.estados = estados;
       this.proyectos = proyectos;
    }
   
    public BigDecimal getCodEstadoproyec() {
        return this.codEstadoproyec;
    }
    
    public void setCodEstadoproyec(BigDecimal codEstadoproyec) {
        this.codEstadoproyec = codEstadoproyec;
    }
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }
    public Proyectos getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Proyectos proyectos) {
        this.proyectos = proyectos;
    }




}


