package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EstadosAsesoria generated by hbm2java
 */
@Entity
@Table(name="estados_asesoria"
    ,schema="public"
)
public class EstadosAsesoria  implements java.io.Serializable {


     private BigDecimal estadoPro;
     private Asesoria asesoria;
     private Estados estados;

    public EstadosAsesoria() {
    }

    public EstadosAsesoria(BigDecimal estadoPro, Asesoria asesoria, Estados estados) {
       this.estadoPro = estadoPro;
       this.asesoria = asesoria;
       this.estados = estados;
    }
   
     @Id 

    
    @Column(name="estado_pro", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getEstadoPro() {
        return this.estadoPro;
    }
    
    public void setEstadoPro(BigDecimal estadoPro) {
        this.estadoPro = estadoPro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_asesoria", nullable=false)
    public Asesoria getAsesoria() {
        return this.asesoria;
    }
    
    public void setAsesoria(Asesoria asesoria) {
        this.asesoria = asesoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_estados", nullable=false)
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }




}


