package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EstadoProyecto generated by hbm2java
 */
@Entity
@Table(name="estado_proyecto"
    ,schema="public"
)
public class EstadoProyecto  implements java.io.Serializable {


     private BigDecimal estaPro;
     private Estados estados;
     private Proyectos proyectos;

    public EstadoProyecto() {
    }

    public EstadoProyecto(BigDecimal estaPro, Estados estados, Proyectos proyectos) {
       this.estaPro = estaPro;
       this.estados = estados;
       this.proyectos = proyectos;
    }
   
     @Id 

    
    @Column(name="esta_pro", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getEstaPro() {
        return this.estaPro;
    }
    
    public void setEstaPro(BigDecimal estaPro) {
        this.estaPro = estaPro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_estados", nullable=false)
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_proyecto", nullable=false)
    public Proyectos getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Proyectos proyectos) {
        this.proyectos = proyectos;
    }




}


