package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Festivos generated by hbm2java
 */
@Entity
@Table(name="festivos"
    ,schema="public"
)
public class Festivos  implements java.io.Serializable {


     private long festivo;
     private AñoFestivo añoFestivo;
     private Date fecha;

    public Festivos() {
    }

	
    public Festivos(long festivo, Date fecha) {
        this.festivo = festivo;
        this.fecha = fecha;
    }
    public Festivos(long festivo, AñoFestivo añoFestivo, Date fecha) {
       this.festivo = festivo;
       this.añoFestivo = añoFestivo;
       this.fecha = fecha;
    }
   
     @Id 

    
    @Column(name="festivo", unique=true, nullable=false, precision=10, scale=0)
    public long getFestivo() {
        return this.festivo;
    }
    
    public void setFestivo(long festivo) {
        this.festivo = festivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_a�o")
    public AñoFestivo getAñoFestivo() {
        return this.añoFestivo;
    }
    
    public void setAñoFestivo(AñoFestivo añoFestivo) {
        this.añoFestivo = añoFestivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=30)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Override
    public String toString() {
        return  ""+festivo;
    }




}


