package Entity;
// Generated 15/10/2015 01:16:32 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Festivos generated by hbm2java
 */
public class Festivos  implements java.io.Serializable {


     private long codigoFestivos;
     private Aofestivo aofestivo;
     private Date fechaFestivo;

    public Festivos() {
    }

	
    public Festivos(long codigoFestivos, Date fechaFestivo) {
        this.codigoFestivos = codigoFestivos;
        this.fechaFestivo = fechaFestivo;
    }
    public Festivos(long codigoFestivos, Aofestivo aofestivo, Date fechaFestivo) {
       this.codigoFestivos = codigoFestivos;
       this.aofestivo = aofestivo;
       this.fechaFestivo = fechaFestivo;
    }
   
    public long getCodigoFestivos() {
        return this.codigoFestivos;
    }
    
    public void setCodigoFestivos(long codigoFestivos) {
        this.codigoFestivos = codigoFestivos;
    }
    public Aofestivo getAofestivo() {
        return this.aofestivo;
    }
    
    public void setAofestivo(Aofestivo aofestivo) {
        this.aofestivo = aofestivo;
    }
    public Date getFechaFestivo() {
        return this.fechaFestivo;
    }
    
    public void setFechaFestivo(Date fechaFestivo) {
        this.fechaFestivo = fechaFestivo;
    }




}


