package Entity;
// Generated 22-jul-2015 14:32:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Festivos generated by hbm2java
 */
public class Festivos  implements java.io.Serializable {


     private BigDecimal codigoFestivos;
     private Aofestivo aofestivo;
     private Disponibilidad disponibilidad;
     private Date fechaFestivo;

    public Festivos() {
    }

    public Festivos(BigDecimal codigoFestivos, Aofestivo aofestivo, Disponibilidad disponibilidad, Date fechaFestivo) {
       this.codigoFestivos = codigoFestivos;
       this.aofestivo = aofestivo;
       this.disponibilidad = disponibilidad;
       this.fechaFestivo = fechaFestivo;
    }
   
    public BigDecimal getCodigoFestivos() {
        return this.codigoFestivos;
    }
    
    public void setCodigoFestivos(BigDecimal codigoFestivos) {
        this.codigoFestivos = codigoFestivos;
    }
    public Aofestivo getAofestivo() {
        return this.aofestivo;
    }
    
    public void setAofestivo(Aofestivo aofestivo) {
        this.aofestivo = aofestivo;
    }
    public Disponibilidad getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Disponibilidad disponibilidad) {
        this.disponibilidad = disponibilidad;
    }
    public Date getFechaFestivo() {
        return this.fechaFestivo;
    }
    
    public void setFechaFestivo(Date fechaFestivo) {
        this.fechaFestivo = fechaFestivo;
    }




}


