package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LogsId generated by hbm2java
 */
@Embeddable
public class LogsId  implements java.io.Serializable {


     private BigDecimal codLogs;
     private BigDecimal pegeId;

    public LogsId() {
    }

    public LogsId(BigDecimal codLogs, BigDecimal pegeId) {
       this.codLogs = codLogs;
       this.pegeId = pegeId;
    }
   


    @Column(name="cod_logs", nullable=false, precision=131089, scale=0)
    public BigDecimal getCodLogs() {
        return this.codLogs;
    }
    
    public void setCodLogs(BigDecimal codLogs) {
        this.codLogs = codLogs;
    }


    @Column(name="pege_id", nullable=false, precision=131089, scale=0)
    public BigDecimal getPegeId() {
        return this.pegeId;
    }
    
    public void setPegeId(BigDecimal pegeId) {
        this.pegeId = pegeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogsId) ) return false;
		 LogsId castOther = ( LogsId ) other; 
         
		 return ( (this.getCodLogs()==castOther.getCodLogs()) || ( this.getCodLogs()!=null && castOther.getCodLogs()!=null && this.getCodLogs().equals(castOther.getCodLogs()) ) )
 && ( (this.getPegeId()==castOther.getPegeId()) || ( this.getPegeId()!=null && castOther.getPegeId()!=null && this.getPegeId().equals(castOther.getPegeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodLogs() == null ? 0 : this.getCodLogs().hashCode() );
         result = 37 * result + ( getPegeId() == null ? 0 : this.getPegeId().hashCode() );
         return result;
   }   


}


