package Entity;
// Generated 15/10/2015 01:16:32 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * NivelDisponible generated by hbm2java
 */
public class NivelDisponible  implements java.io.Serializable {


     private BigDecimal codigoNivel;
     private Disponibilidad disponibilidad;
     private String semestre;

    public NivelDisponible() {
    }

    public NivelDisponible(BigDecimal codigoNivel, Disponibilidad disponibilidad, String semestre) {
       this.codigoNivel = codigoNivel;
       this.disponibilidad = disponibilidad;
       this.semestre = semestre;
    }
   
    public BigDecimal getCodigoNivel() {
        return this.codigoNivel;
    }
    
    public void setCodigoNivel(BigDecimal codigoNivel) {
        this.codigoNivel = codigoNivel;
    }
    public Disponibilidad getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Disponibilidad disponibilidad) {
        this.disponibilidad = disponibilidad;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }




}


