package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Objetivos generated by hbm2java
 */
@Entity
@Table(name="objetivos"
    ,schema="public"
)
public class Objetivos  implements java.io.Serializable {


     private long codObjetivo;
     private Proyectos proyectos;
     private String descripcion;

    public Objetivos() {
    }

	
    public Objetivos(long codObjetivo, String descripcion) {
        this.codObjetivo = codObjetivo;
        this.descripcion = descripcion;
    }
    public Objetivos(long codObjetivo, Proyectos proyectos, String descripcion) {
       this.codObjetivo = codObjetivo;
       this.proyectos = proyectos;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="cod_objetivo", unique=true, nullable=false, precision=10, scale=0)
    public long getCodObjetivo() {
        return this.codObjetivo;
    }
    
    public void setCodObjetivo(long codObjetivo) {
        this.codObjetivo = codObjetivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_proyecto")
    public Proyectos getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Proyectos proyectos) {
        this.proyectos = proyectos;
    }

    
    @Column(name="descripcion", nullable=false, length=3000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


