package Entity;
// Generated 02-jun-2015 13:38:41 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,schema="public"
)
public class Persona  implements java.io.Serializable {


     private BigDecimal idpersona;
     private Usuario usuario;
     private String nombres;
     private String apellidos;
     private Set telefonoses = new HashSet(0);
     private Set correospersonas = new HashSet(0);

    public Persona() {
    }

	
    public Persona(BigDecimal idpersona, Usuario usuario, String nombres, String apellidos) {
        this.idpersona = idpersona;
        this.usuario = usuario;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Persona(BigDecimal idpersona, Usuario usuario, String nombres, String apellidos, Set telefonoses, Set correospersonas) {
       this.idpersona = idpersona;
       this.usuario = usuario;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefonoses = telefonoses;
       this.correospersonas = correospersonas;
    }
   
     @Id 

    
    @Column(name="idpersona", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(BigDecimal idpersona) {
        this.idpersona = idpersona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pege_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombres", nullable=false)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getTelefonoses() {
        return this.telefonoses;
    }
    
    public void setTelefonoses(Set telefonoses) {
        this.telefonoses = telefonoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set getCorreospersonas() {
        return this.correospersonas;
    }
    
    public void setCorreospersonas(Set correospersonas) {
        this.correospersonas = correospersonas;
    }




}


