package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proyectos generated by hbm2java
 */
@Entity
@Table(name="proyectos"
    ,schema="public"
)
public class Proyectos  implements java.io.Serializable {


     private BigDecimal codigoProyecto;
     private String nombre;
     private String ruta;
     private String calificacion;
     private Set revisionProyectos = new HashSet(0);
     private Set usuarioProyectos = new HashSet(0);
     private Set estadoProyectos = new HashSet(0);

    public Proyectos() {
    }

	
    public Proyectos(BigDecimal codigoProyecto, String nombre, String ruta, String calificacion) {
        this.codigoProyecto = codigoProyecto;
        this.nombre = nombre;
        this.ruta = ruta;
        this.calificacion = calificacion;
    }
    public Proyectos(BigDecimal codigoProyecto, String nombre, String ruta, String calificacion, Set revisionProyectos, Set usuarioProyectos, Set estadoProyectos) {
       this.codigoProyecto = codigoProyecto;
       this.nombre = nombre;
       this.ruta = ruta;
       this.calificacion = calificacion;
       this.revisionProyectos = revisionProyectos;
       this.usuarioProyectos = usuarioProyectos;
       this.estadoProyectos = estadoProyectos;
    }
   
     @Id 

    
    @Column(name="codigo_proyecto", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodigoProyecto() {
        return this.codigoProyecto;
    }
    
    public void setCodigoProyecto(BigDecimal codigoProyecto) {
        this.codigoProyecto = codigoProyecto;
    }

    
    @Column(name="nombre", nullable=false, length=250)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ruta", nullable=false, length=250)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="calificacion", nullable=false, length=10)
    public String getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyectos")
    public Set getRevisionProyectos() {
        return this.revisionProyectos;
    }
    
    public void setRevisionProyectos(Set revisionProyectos) {
        this.revisionProyectos = revisionProyectos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyectos")
    public Set getUsuarioProyectos() {
        return this.usuarioProyectos;
    }
    
    public void setUsuarioProyectos(Set usuarioProyectos) {
        this.usuarioProyectos = usuarioProyectos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyectos")
    public Set getEstadoProyectos() {
        return this.estadoProyectos;
    }
    
    public void setEstadoProyectos(Set estadoProyectos) {
        this.estadoProyectos = estadoProyectos;
    }




}


