package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RevisionProyecto generated by hbm2java
 */
@Entity
@Table(name="revision_proyecto"
    ,schema="public"
)
public class RevisionProyecto  implements java.io.Serializable {


     private BigDecimal codRevisionproyecto;
     private Proyectos proyectos;
     private Revisiones revisiones;

    public RevisionProyecto() {
    }

    public RevisionProyecto(BigDecimal codRevisionproyecto, Proyectos proyectos, Revisiones revisiones) {
       this.codRevisionproyecto = codRevisionproyecto;
       this.proyectos = proyectos;
       this.revisiones = revisiones;
    }
   
     @Id 

    
    @Column(name="cod_revisionproyecto", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodRevisionproyecto() {
        return this.codRevisionproyecto;
    }
    
    public void setCodRevisionproyecto(BigDecimal codRevisionproyecto) {
        this.codRevisionproyecto = codRevisionproyecto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_proyecto", nullable=false)
    public Proyectos getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Proyectos proyectos) {
        this.proyectos = proyectos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_revision", nullable=false)
    public Revisiones getRevisiones() {
        return this.revisiones;
    }
    
    public void setRevisiones(Revisiones revisiones) {
        this.revisiones = revisiones;
    }




}


