package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolActividad generated by hbm2java
 */
@Entity
@Table(name="rol_actividad"
    ,schema="public"
)
public class RolActividad  implements java.io.Serializable {


     private BigDecimal rolActivi;
     private Actividades actividades;
     private Rol rol;

    public RolActividad() {
    }

    public RolActividad(BigDecimal rolActivi, Actividades actividades, Rol rol) {
       this.rolActivi = rolActivi;
       this.actividades = actividades;
       this.rol = rol;
    }
   
     @Id 

    
    @Column(name="rol_activi", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getRolActivi() {
        return this.rolActivi;
    }
    
    public void setRolActivi(BigDecimal rolActivi) {
        this.rolActivi = rolActivi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_actividad", nullable=false)
    public Actividades getActividades() {
        return this.actividades;
    }
    
    public void setActividades(Actividades actividades) {
        this.actividades = actividades;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_rol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


