package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tareas generated by hbm2java
 */
@Entity
@Table(name="tareas"
    ,schema="public"
)
public class Tareas  implements java.io.Serializable {


     private long codTarea;
     private Asesoria asesoria;
     private String responsable;
     private String tarea;

    public Tareas() {
    }

	
    public Tareas(long codTarea, String responsable, String tarea) {
        this.codTarea = codTarea;
        this.responsable = responsable;
        this.tarea = tarea;
    }
    public Tareas(long codTarea, Asesoria asesoria, String responsable, String tarea) {
       this.codTarea = codTarea;
       this.asesoria = asesoria;
       this.responsable = responsable;
       this.tarea = tarea;
    }
   
     @Id 

    
    @Column(name="cod_tarea", unique=true, nullable=false, precision=10, scale=0)
    public long getCodTarea() {
        return this.codTarea;
    }
    
    public void setCodTarea(long codTarea) {
        this.codTarea = codTarea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_asesoria")
    public Asesoria getAsesoria() {
        return this.asesoria;
    }
    
    public void setAsesoria(Asesoria asesoria) {
        this.asesoria = asesoria;
    }

    
    @Column(name="responsable", nullable=false, length=50)
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }

    
    @Column(name="tarea", nullable=false, length=2000)
    public String getTarea() {
        return this.tarea;
    }
    
    public void setTarea(String tarea) {
        this.tarea = tarea;
    }




}


