package Entity;
// Generated 13-ago-2015 17:28:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Telefonos generated by hbm2java
 */
public class Telefonos  implements java.io.Serializable {


     private BigDecimal codTelefono;
     private Persona persona;
     private String telefono;
     private String ciudad;
     private boolean tipo;

    public Telefonos() {
    }

    public Telefonos(BigDecimal codTelefono, Persona persona, String telefono, String ciudad, boolean tipo) {
       this.codTelefono = codTelefono;
       this.persona = persona;
       this.telefono = telefono;
       this.ciudad = ciudad;
       this.tipo = tipo;
    }
   
    public BigDecimal getCodTelefono() {
        return this.codTelefono;
    }
    
    public void setCodTelefono(BigDecimal codTelefono) {
        this.codTelefono = codTelefono;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public boolean isTipo() {
        return this.tipo;
    }
    
    public void setTipo(boolean tipo) {
        this.tipo = tipo;
    }




}


