package Entity;
// Generated 22-jul-2015 14:32:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoProyecto generated by hbm2java
 */
public class TipoProyecto  implements java.io.Serializable {


     private long codTipo;
     private String descripcion;
     private Set proyectoses = new HashSet(0);

    public TipoProyecto() {
    }

	
    public TipoProyecto(long codTipo, String descripcion) {
        this.codTipo = codTipo;
        this.descripcion = descripcion;
    }
    public TipoProyecto(long codTipo, String descripcion, Set proyectoses) {
       this.codTipo = codTipo;
       this.descripcion = descripcion;
       this.proyectoses = proyectoses;
    }
   
    public long getCodTipo() {
        return this.codTipo;
    }
    
    public void setCodTipo(long codTipo) {
        this.codTipo = codTipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProyectoses() {
        return this.proyectoses;
    }
    
    public void setProyectoses(Set proyectoses) {
        this.proyectoses = proyectoses;
    }




}


