package Entity;
// Generated 31-jul-2015 12:11:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoProyecto generated by hbm2java
 */
@Entity
@Table(name="tipo_proyecto"
    ,schema="public"
)
public class TipoProyecto  implements java.io.Serializable {


     private long codTipo;
     private String descripcion;
     private Set proyectoses = new HashSet(0);

    public TipoProyecto() {
    }

	
    public TipoProyecto(long codTipo, String descripcion) {
        this.codTipo = codTipo;
        this.descripcion = descripcion;
    }
    public TipoProyecto(long codTipo, String descripcion, Set proyectoses) {
       this.codTipo = codTipo;
       this.descripcion = descripcion;
       this.proyectoses = proyectoses;
    }
   
     @Id 

    
    @Column(name="cod_tipo", unique=true, nullable=false, precision=10, scale=0)
    public long getCodTipo() {
        return this.codTipo;
    }
    
    public void setCodTipo(long codTipo) {
        this.codTipo = codTipo;
    }

    
    @Column(name="descripcion", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoProyecto")
    public Set getProyectoses() {
        return this.proyectoses;
    }
    
    public void setProyectoses(Set proyectoses) {
        this.proyectoses = proyectoses;
    }




}


