package Entity;
// Generated 18-ago-2015 14:13:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Ubicacion generated by hbm2java
 */
public class Ubicacion  implements java.io.Serializable {


     private BigDecimal ubicacion;
     private String sede;
     private String salon;
     private Set asesorias = new HashSet(0);

    public Ubicacion() {
    }

	
    public Ubicacion(BigDecimal ubicacion, String sede, String salon) {
        this.ubicacion = ubicacion;
        this.sede = sede;
        this.salon = salon;
    }
    public Ubicacion(BigDecimal ubicacion, String sede, String salon, Set asesorias) {
       this.ubicacion = ubicacion;
       this.sede = sede;
       this.salon = salon;
       this.asesorias = asesorias;
    }
   
    public BigDecimal getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(BigDecimal ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getSede() {
        return this.sede;
    }
    
    public void setSede(String sede) {
        this.sede = sede;
    }
    public String getSalon() {
        return this.salon;
    }
    
    public void setSalon(String salon) {
        this.salon = salon;
    }
    public Set getAsesorias() {
        return this.asesorias;
    }
    
    public void setAsesorias(Set asesorias) {
        this.asesorias = asesorias;
    }




}


