package Entity;
// Generated 19-may-2015 18:40:29 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioProyecto generated by hbm2java
 */
@Entity
@Table(name="usuario_proyecto"
    ,schema="public"
)
public class UsuarioProyecto  implements java.io.Serializable {


     private BigDecimal usuarioPro;
     private Usuario usuario;
     private Proyectos proyectos;

    public UsuarioProyecto() {
    }

    public UsuarioProyecto(BigDecimal usuarioPro, Usuario usuario, Proyectos proyectos) {
       this.usuarioPro = usuarioPro;
       this.usuario = usuario;
       this.proyectos = proyectos;
    }
   
     @Id 

    
    @Column(name="usuario_pro", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getUsuarioPro() {
        return this.usuarioPro;
    }
    
    public void setUsuarioPro(BigDecimal usuarioPro) {
        this.usuarioPro = usuarioPro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pege_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_proyecto", nullable=false)
    public Proyectos getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Proyectos proyectos) {
        this.proyectos = proyectos;
    }




}


