package Entity;
// Generated 02-jun-2015 13:38:41 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuRol generated by hbm2java
 */
@Entity
@Table(name="usu_rol"
    ,schema="public"
)
public class UsuRol  implements java.io.Serializable {


     private BigDecimal codUsurol;
     private Usuario usuario;
     private Rol rol;

    public UsuRol() {
    }

    public UsuRol(BigDecimal codUsurol, Usuario usuario, Rol rol) {
       this.codUsurol = codUsurol;
       this.usuario = usuario;
       this.rol = rol;
    }
   
     @Id 

    
    @Column(name="cod_usurol", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getCodUsurol() {
        return this.codUsurol;
    }
    
    public void setCodUsurol(BigDecimal codUsurol) {
        this.codUsurol = codUsurol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pege_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_rol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


