package Entity;
// Generated 18-ago-2015 14:13:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Versiones generated by hbm2java
 */
public class Versiones  implements java.io.Serializable {


     private long codVersion;
     private Proyectos proyectos;
     private String nombre;
     private String rutaArchivo;
     private Date fecha;

    public Versiones() {
    }

	
    public Versiones(long codVersion, String nombre, String rutaArchivo, Date fecha) {
        this.codVersion = codVersion;
        this.nombre = nombre;
        this.rutaArchivo = rutaArchivo;
        this.fecha = fecha;
    }
    public Versiones(long codVersion, Proyectos proyectos, String nombre, String rutaArchivo, Date fecha) {
       this.codVersion = codVersion;
       this.proyectos = proyectos;
       this.nombre = nombre;
       this.rutaArchivo = rutaArchivo;
       this.fecha = fecha;
    }
   
    public long getCodVersion() {
        return this.codVersion;
    }
    
    public void setCodVersion(long codVersion) {
        this.codVersion = codVersion;
    }
    public Proyectos getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Proyectos proyectos) {
        this.proyectos = proyectos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRutaArchivo() {
        return this.rutaArchivo;
    }
    
    public void setRutaArchivo(String rutaArchivo) {
        this.rutaArchivo = rutaArchivo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


